
#define CLEAN2 1

#define SHORT_CLASS_NAMES

#define REMOVE_UNUSED_FUNCTIONS
#define OPTIMISE_STRICT_RHS_SELECTORS

#define STORE_STRICT_CALL_NODES 1
#undef OBSERVE_ARRAY_SELECTS_IN_PATTERN

#define ABSTRACT_OBJECT 1 /* bug fix */

#define TRANSFORM_PATTERNS_BEFORE_STRICTNESS_ANALYSIS
#define IMPORT_OBJ_AND_LIB 1

#define WRITE_DCL_MODIFICATION_TIME 1

#define SA_RECOGNIZES_ABORT_AND_UNDEF 1

#define STRICT_LISTS 1
#define BOXED_RECORDS 1

#define NEW_APPLY

#define KARBON

#define NEW_SELECTOR_DESCRIPTORS
